-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               5.7.11-0ubuntu6 - (Ubuntu)
-- Server OS:                    Linux
-- HeidiSQL Version:             10.2.0.5599
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- Dumping structure for table tvz.countries
CREATE TABLE IF NOT EXISTS `countries` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `iso` char(2) DEFAULT NULL,
  `country_name` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `iso` (`iso`),
  KEY `country` (`country_name`)
) ENGINE=InnoDB AUTO_INCREMENT=246 DEFAULT CHARSET=utf8;

-- Dumping data for table tvz.countries: ~245 rows (approximately)

/*!40000 ALTER TABLE `countries` DISABLE KEYS */;
INSERT INTO `countries` (`id`, `iso`, `country_name`) VALUES
    (1, 'af', 'Afghanistan'),
    (2, 'al', 'Albania'),
    (3, 'dz', 'Algeria'),
    (4, 'ds', 'American Samoa'),
    (5, 'ad', 'Andorra'),
    (6, 'ao', 'Angola'),
    (7, 'ai', 'Anguilla'),
    (8, 'aq', 'Antarctica'),
    (9, 'ag', 'Antigua and Barbuda'),
    (10, 'ar', 'Argentina'),
    (11, 'am', 'Armenia'),
    (12, 'aw', 'Aruba'),
    (13, 'au', 'Australia'),
    (14, 'at', 'Austria'),
    (15, 'az', 'Azerbaijan'),
    (16, 'bs', 'Bahamas'),
    (17, 'bh', 'Bahrain'),
    (18, 'bd', 'Bangladesh'),
    (19, 'bb', 'Barbados'),
    (20, 'by', 'Belarus'),
    (21, 'be', 'Belgium'),
    (22, 'bz', 'Belize'),
    (23, 'bj', 'Benin'),
    (24, 'bm', 'Bermuda'),
    (25, 'bt', 'Bhutan'),
    (26, 'bo', 'Bolivia'),
    (27, 'ba', 'Bosnia and Herzegovina'),
    (28, 'bw', 'Botswana'),
    (29, 'bv', 'Bouvet Island'),
    (30, 'br', 'Brazil'),
    (31, 'io', 'British Indian Ocean Territory'),
    (32, 'bn', 'Brunei Darussalam'),
    (33, 'bg', 'Bulgaria'),
    (34, 'bf', 'Burkina Faso'),
    (35, 'bi', 'Burundi'),
    (36, 'kh', 'Cambodia'),
    (37, 'cm', 'Cameroon'),
    (38, 'ca', 'Canada'),
    (39, 'cv', 'Cape Verde'),
    (40, 'ky', 'Cayman Islands'),
    (41, 'cf', 'Central African Republic'),
    (42, 'td', 'Chad'),
    (43, 'cl', 'Chile'),
    (44, 'cn', 'China'),
    (45, 'cx', 'Christmas Island'),
    (46, 'cc', 'Cocos (Keeling) Islands'),
    (47, 'co', 'Colombia'),
    (48, 'km', 'Comoros'),
    (49, 'cg', 'Congo'),
    (50, 'ck', 'Cook Islands'),
    (51, 'cr', 'Costa Rica'),
    (52, 'hr', 'Croatia (Hrvatska)'),
    (53, 'cu', 'Cuba'),
    (54, 'cy', 'Cyprus'),
    (55, 'cz', 'Czech Republic'),
    (56, 'dk', 'Denmark'),
    (57, 'dj', 'Djibouti'),
    (58, 'dm', 'Dominica'),
    (59, 'do', 'Dominican Republic'),
    (60, 'tp', 'East Timor'),
    (61, 'ec', 'Ecuador'),
    (62, 'eg', 'Egypt'),
    (63, 'sv', 'El Salvador'),
    (64, 'gq', 'Equatorial Guinea'),
    (65, 'er', 'Eritrea'),
    (66, 'ee', 'Estonia'),
    (67, 'et', 'Ethiopia'),
    (68, 'fk', 'Falkland Islands (Malvinas)'),
    (69, 'fo', 'Faroe Islands'),
    (70, 'fj', 'Fiji'),
    (71, 'fi', 'Finland'),
    (72, 'fr', 'France'),
    (73, 'fx', 'France, Metropolitan'),
    (74, 'gf', 'French Guiana'),
    (75, 'pf', 'French Polynesia'),
    (76, 'tf', 'French Southern Territories'),
    (77, 'ga', 'Gabon'),
    (78, 'gm', 'Gambia'),
    (79, 'ge', 'Georgia'),
    (80, 'de', 'Germany'),
    (81, 'gh', 'Ghana'),
    (82, 'gi', 'Gibraltar'),
    (83, 'gk', 'Guernsey'),
    (84, 'gr', 'Greece'),
    (85, 'gl', 'Greenland'),
    (86, 'gd', 'Grenada'),
    (87, 'gp', 'Guadeloupe'),
    (88, 'gu', 'Guam'),
    (89, 'gt', 'Guatemala'),
    (90, 'gn', 'Guinea'),
    (91, 'gw', 'Guinea-Bissau'),
    (92, 'gy', 'Guyana'),
    (93, 'ht', 'Haiti'),
    (94, 'hm', 'Heard and Mc Donald Islands'),
    (95, 'hn', 'Honduras'),
    (96, 'hk', 'Hong Kong'),
    (97, 'hu', 'Hungary'),
    (98, 'is', 'Iceland'),
    (99, 'in', 'India'),
    (100, 'im', 'Isle of Man'),
    (101, 'id', 'Indonesia'),
    (102, 'ir', 'Iran (Islamic Republic of)'),
    (103, 'iq', 'Iraq'),
    (104, 'ie', 'Ireland'),
    (105, 'il', 'Israel'),
    (106, 'it', 'Italy'),
    (107, 'ci', 'Ivory Coast'),
    (108, 'je', 'Jersey'),
    (109, 'jm', 'Jamaica'),
    (110, 'jp', 'Japan'),
    (111, 'jo', 'Jordan'),
    (112, 'kz', 'Kazakhstan'),
    (113, 'ke', 'Kenya'),
    (114, 'ki', 'Kiribati'),
    (115, 'kp', 'Korea, Democratic People\'s Republic of'),
    (116, 'kr', 'Korea, Republic of'),
    (117, 'xk', 'Kosovo'),
    (118, 'kw', 'Kuwait'),
    (119, 'kg', 'Kyrgyzstan'),
    (120, 'la', 'Lao People\'s Democratic Republic'),
    (121, 'lv', 'Latvia'),
    (122, 'lb', 'Lebanon'),
    (123, 'ls', 'Lesotho'),
    (124, 'lr', 'Liberia'),
    (125, 'ly', 'Libyan Arab Jamahiriya'),
    (126, 'li', 'Liechtenstein'),
    (127, 'lt', 'Lithuania'),
    (128, 'lu', 'Luxembourg'),
    (129, 'mo', 'Macau'),
    (130, 'mk', 'North Macedonia'),
    (131, 'mg', 'Madagascar'),
    (132, 'mw', 'Malawi'),
    (133, 'my', 'Malaysia'),
    (134, 'mv', 'Maldives'),
    (135, 'ml', 'Mali'),
    (136, 'mt', 'Malta'),
    (137, 'mh', 'Marshall Islands'),
    (138, 'mq', 'Martinique'),
    (139, 'mr', 'Mauritania'),
    (140, 'mu', 'Mauritius'),
    (141, 'ty', 'Mayotte'),
    (142, 'mx', 'Mexico'),
    (143, 'fm', 'Micronesia, Federated States of'),
    (144, 'md', 'Moldova, Republic of'),
    (145, 'mc', 'Monaco'),
    (146, 'mn', 'Mongolia'),
    (147, 'me', 'Montenegro'),
    (148, 'ms', 'Montserrat'),
    (149, 'ma', 'Morocco'),
    (150, 'mz', 'Mozambique'),
    (151, 'mm', 'Myanmar'),
    (152, 'na', 'Namibia'),
    (153, 'nr', 'Nauru'),
    (154, 'np', 'Nepal'),
    (155, 'nl', 'Netherlands'),
    (156, 'an', 'Netherlands Antilles'),
    (157, 'nc', 'New Caledonia'),
    (158, 'nz', 'New Zealand'),
    (159, 'ni', 'Nicaragua'),
    (160, 'ne', 'Niger'),
    (161, 'ng', 'Nigeria'),
    (162, 'nu', 'Niue'),
    (163, 'nf', 'Norfolk Island'),
    (164, 'mp', 'Northern Mariana Islands'),
    (165, 'no', 'Norway'),
    (166, 'om', 'Oman'),
    (167, 'pk', 'Pakistan'),
    (168, 'pw', 'Palau'),
    (169, 'ps', 'Palestine'),
    (170, 'pa', 'Panama'),
    (171, 'pg', 'Papua New Guinea'),
    (172, 'py', 'Paraguay'),
    (173, 'pe', 'Peru'),
    (174, 'ph', 'Philippines'),
    (175, 'pn', 'Pitcairn'),
    (176, 'pl', 'Poland'),
    (177, 'pt', 'Portugal'),
    (178, 'pr', 'Puerto Rico'),
    (179, 'qa', 'Qatar'),
    (180, 're', 'Reunion'),
    (181, 'ro', 'Romania'),
    (182, 'ru', 'Russian Federation'),
    (183, 'rw', 'Rwanda'),
    (184, 'kn', 'Saint Kitts and Nevis'),
    (185, 'lc', 'Saint Lucia'),
    (186, 'vc', 'Saint Vincent and the Grenadines'),
    (187, 'ws', 'Samoa'),
    (188, 'sm', 'San Marino'),
    (189, 'st', 'Sao Tome and Principe'),
    (190, 'sa', 'Saudi Arabia'),
    (191, 'sn', 'Senegal'),
    (192, 'rs', 'Serbia'),
    (193, 'sc', 'Seychelles'),
    (194, 'sl', 'Sierra Leone'),
    (195, 'sg', 'Singapore'),
    (196, 'sk', 'Slovakia'),
    (197, 'si', 'Slovenia'),
    (198, 'sb', 'Solomon Islands'),
    (199, 'so', 'Somalia'),
    (200, 'za', 'South Africa'),
    (201, 'gs', 'South Georgia South Sandwich Islands'),
    (202, 'es', 'Spain'),
    (203, 'lk', 'Sri Lanka'),
    (204, 'sh', 'St. Helena'),
    (205, 'pm', 'St. Pierre and Miquelon'),
    (206, 'sd', 'Sudan'),
    (207, 'sr', 'Suriname'),
    (208, 'sj', 'Svalbard and Jan Mayen Islands'),
    (209, 'sz', 'Swaziland'),
    (210, 'se', 'Sweden'),
    (211, 'ch', 'Switzerland'),
    (212, 'sy', 'Syrian Arab Republic'),
    (213, 'tw', 'Taiwan'),
    (214, 'tj', 'Tajikistan'),
    (215, 'tz', 'Tanzania, United Republic of'),
    (216, 'th', 'Thailand'),
    (217, 'tg', 'Togo'),
    (218, 'tk', 'Tokelau'),
    (219, 'to', 'Tonga'),
    (220, 'tt', 'Trinidad and Tobago'),
    (221, 'tn', 'Tunisia'),
    (222, 'tr', 'Turkey'),
    (223, 'tm', 'Turkmenistan'),
    (224, 'tc', 'Turks and Caicos Islands'),
    (225, 'tv', 'Tuvalu'),
    (226, 'ug', 'Uganda'),
    (227, 'ua', 'Ukraine'),
    (228, 'ae', 'United Arab Emirates'),
    (229, 'gb', 'United Kingdom'),
    (230, 'us', 'United States'),
    (231, 'um', 'United States minor outlying islands'),
    (232, 'uy', 'Uruguay'),
    (233, 'uz', 'Uzbekistan'),
    (234, 'vu', 'Vanuatu'),
    (235, 'va', 'Vatican City State'),
    (236, 've', 'Venezuela'),
    (237, 'vn', 'Vietnam'),
    (238, 'vg', 'Virgin Islands (British)'),
    (239, 'vi', 'Virgin Islands (U.S.)'),
    (240, 'wf', 'Wallis and Futuna Islands'),
    (241, 'eh', 'Western Sahara'),
    (242, 'ye', 'Yemen'),
    (243, 'zr', 'Zaire'),
    (244, 'zm', 'Zambia'),
    (245, 'zw', 'Zimbabwe');
/*!40000 ALTER TABLE `countries` ENABLE KEYS */;